services:
    # Serviço da API (Laravel)
    api:
        container_name: api
        build:
            context: .
            dockerfile: ./docker/php/main/Dockerfile
        restart: always
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - db
            - httpserver
        networks:
            - app-network

    # Banco de Dados PostgreSQL
    db:
        container_name: postgres
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_HOST_AUTH_METHOD: trust
            PGDATA: /data/postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network

    # Servidor Nginx
    httpserver:
        container_name: nginxServer
        image: nginx:alpine
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/main/conf.d/:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

volumes:
    postgres:

networks:
    app-network:
        driver: bridge