services:
    # api
    api:
        container_name: api
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        restart: always
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - db
            - httpserver
        networks:
            - app-network  # Conectando ao app-network

    # postgreSQL
    db:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: $DB_DATABASE # values defined in .env
            POSTGRES_PASSWORD: $DB_PASSWORD # values defined in .env
            POSTGRES_HOST_AUTH_METHOD: trust
            PGDATA: /data/postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network  # Conectando ao app-network

    # nginx
    httpserver:
        container_name: nginxServer
        image: nginx:alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/default.conf
        networks:
            - app-network  # Conectando ao app-network

volumes:
    postgres:
    cache:
        driver: local

networks:
    app-network:
        driver: bridge  # Usando driver bridge para a rede
